name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: Your_password123
          ACCEPT_EULA: Y
        ports:
          - 1433:1433
        options: >-
          --health-cmd " /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your_password123 -Q 'SELECT 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore and build API
        run: dotnet build

      - name: Run API tests
        run: dotnet test

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install client dependencies
        run: npm install
        working-directory: client

      - name: Lint client code
        run: npm run lint
        working-directory: client

      - name: Build client
        run: npm run build
        working-directory: client

      # Optionally run client tests if configured
      - name: Run client tests
        if: false # set to true once jest/vitest is configured
        run: npm test
        working-directory: client